name: Handle Form Submission

on:
  repository_dispatch:
    types: [ form_submission ]

jobs:
  process_submission:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Handle the form data
      run: |
        echo "Name: ${{ github.event.client_payload.name }}"
        echo "Email: ${{ github.event.client_payload.email }}"
        echo "Age: ${{ github.event.client_payload.age }}"

    - name: Save the uploaded file
      run: |
        echo "File upload detected"
        echo "${{ github.event.client_payload.file }}"

        # Here we simulate saving the file uploaded with form submission
        curl -L -o uploaded_file.txt "${{ github.event.client_payload.file }}"

    - name: Upload file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: form-submission-file
        path: ./uploaded_file.txt
